name: Build and deploy .NET application to container app deed
on:
  push:
    branches:
    - master
permissions:
  id-token: write
  contents: read
env:
  CONTAINER_APP_CONTAINER_NAME: deed
  CONTAINER_APP_NAME: deed
  CONTAINER_APP_RESOURCE_GROUP_NAME: deed-rg
  CONTAINER_REGISTRY_LOGIN_SERVER: deedregistry.azurecr.io
  DOCKER_FILE_PATH: Deed.Api/Dockerfile
  PROJECT_NAME_FOR_DOCKER: deed.api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Login to ACR
      run: az acr login --name deedregistry

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.deed_CLIENT_ID_2475 }}
        tenant-id: ${{ vars.deed_TENANT_ID_2475 }}
        subscription-id: ${{ vars.deed_SUBSCRIPTION_ID_2475 }}
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.deedregistry_USERNAME_2475 }} --password ${{ secrets.deedregistry_PASSWORD_2475 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
