services:
  deed.api:
    image: ${DOCKER_REGISTRY-}deedapi
    build:
      context: .
      dockerfile: Deed.Api/Dockerfile
    depends_on:
      - deed.db
    environment:
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8000:8000"
      - "8001:8001"
  
  deed.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd."
    volumes:
      - ./mssql-data:/var/opt/mssql/data
    ports:
      - "8002:1433"
